feat: add support for mutiny based reactive endpoints
mcollovati/quarkus-hilla pull request #1091
Opened 2024-11-23 17:15 UTC by mcollovati

Allows Hilla endpoints to specify Mutiny Multi as return type for reactive endpoints. Also introduces MutinyEndpointSubscription as a Mutiny alternative to Hilla EndpointSubscription to provide unsubscribe callback.

Fixes #1028

2025-01-20 23:02 UTC, Dudeplayz requested changes
Locally tested with example project. Works perfectly.
Just one rename request since last review is open, then it can be merged. Good job!

2025-01-21 04:04 UTC, mcollovati commented on commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/TransferTypesPluginClassVisitor.java
> +                        return;
Good point.
Tests should find out problems, but a project using an incompatible Hilla version would probably fail at build frontend with cryptical error messages. Better throw with an understandable message

2025-01-21 04:07 UTC, mcollovati commented on commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/build/TransferTypesPluginPatch.java
> +    }
Yes, but when using the embedded Vaadin plugin the tranformed classes are not available on classpath, so the patch is temporarily done by reflection.

2025-01-30 16:14 UTC, mcollovati commented on commons/deployment/src/main/java/com/github/mcollovati/quarkus/hilla/deployment/asm/TransferTypesPluginClassVisitor.java
> +                        return;
done

2025-01-30 16:14 UTC, mcollovati commented on commons/runtime/src/main/java/com/github/mcollovati/quarkus/hilla/MutinyEndpointSubscription.java
> +        return new MutinyEndpointSubscription<>(flux, onDisconnect);
done

2025-01-30 21:44 UTC, Dudeplayz submitted a review, later dismissed

2025-02-05 21:34 UTC, Dudeplayz submitted a review, later dismissed

2025-02-06 07:07 UTC, merged