chore: add compatibility matrix
mcollovati/quarkus-hilla pull request #128
Opened 2023-06-19 15:19 UTC by Dudeplayz

2023-06-19 19:25 UTC, mcollovati requested changes

2023-06-19 19:25 UTC, mcollovati commented on README.md
> +| [![Maven Central](https://img.shields.io/maven-central/v/com.github.mcollovati/quarkus-hilla?style=for-the-badge&versionPrefix=1)](https://central.sonatype.com/artifact/com.github.mcollovati/quarku
typo?
```suggestion
| [![Maven Central](https://img.shields.io/maven-central/v/com.github.mcollovati/quarkus-hilla?style=for-the-badge&versionPrefix=1)](https://central.sonatype.com/artifact/com.github.mcollovati/quarkus-hilla) | ![Static Badge](https://img.shields.io/badge/QUARKUS-v2.16%2B-blue?style=for-the-badge&logo=Quarkus) | ![Static Badge](https://img.shields.io/badge/HILLA-v1.3%2B-blue?style=for-the-badge&logo=Vaadin) | ![Static Badge](https://img.shields.io/badge/FLOW-v23.3%2B-blue?style=for-the-badge&logo=Vaadin) |
```

2023-06-19 19:25 UTC, mcollovati commented on README.md
> +| [![Maven Central](https://img.shields.io/maven-central/v/com.github.mcollovati/quarkus-hilla?style=for-the-badge&versionPrefix=1)](https://central.sonatype.com/artifact/com.github.mcollovati/quarku
It would be good to replace `[Static Badge]` with the correct alternative text, e.g. for Hilla badge `[Hilla 2.1+]`

2023-06-19 19:25 UTC, mcollovati commented on README.md
I noticed that images without links are rendered as links anyway.
I wonder if it is better to use the `<picture>` plug `<img>`

```
<picture><img alt="Hilla 2.1+" src="https://img.shields.io/badge/HILLA-v2.1%2B-blue?style=for-the-badge&logo=Vaadin"></picture>
```

<picture><img alt="Hilla 2.1+" src="https://img.shields.io/badge/HILLA-v2.1%2B-blue?style=for-the-badge&logo=Vaadin"></picture>

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

2023-06-19 20:21 UTC, Dudeplayz commented on README.md
> +| [![Maven Central](https://img.shields.io/maven-central/v/com.github.mcollovati/quarkus-hilla?style=for-the-badge&versionPrefix=1)](https://central.sonatype.com/artifact/com.github.mcollovati/quarku
Yes, good catch!

2023-06-19 21:06 UTC, Dudeplayz commented on README.md
Applied.

2023-06-20 04:22 UTC, mcollovati approved these changes

2023-06-20 04:26 UTC, merged